class LEDS(object):
    PIXEL_AMOUNT = 288
    NOTE_AMOUNT = 78

    DOUBLE_LED_NOTE_AMOUNT = 16
    FIRST_OCTAVE_PIXEL_COUNT = 12 * 2
    SECOND_OCTAVE_DOUBLE_LED_PIXEL_COUNT = (DOUBLE_LED_NOTE_AMOUNT - 12) * 2
    SECOND_OCTAVE_PIXEL_COUNT = SECOND_OCTAVE_DOUBLE_LED_PIXEL_COUNT + (12 - (DOUBLE_LED_NOTE_AMOUNT - 12)) * 4
    NORMAL_OCTAVE_PIXEL_COUNT = 12 * 4
